apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
  namespace: scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: selenium-chrome
          image: seleniarm/standalone-chromium:latest
          ports:
            - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  namespace: scrapper
spec:
  type: NodePort
  selector:
    app: selenium-chrome
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30000
