apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-gateway-server
  template:
    metadata:
      labels:
        app: flask-gateway-server
    spec:
      containers:
      - name: flask-gateway-server
        image: network-scapper:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-gateway-server
spec:
  selector:
    app: flask-gateway-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort